### ISSUE TITLE
NHANES accelerometer data analysis

### ISSUE THREAD

**Issue by informaton** [wadpac/oss-dev-webinar-series-pb-field#15]
This is for the webinar on 9/2/2020.    

Here is the working draft of my [google slides](https://docs.google.com/presentation/d/e/2PACX-1vRUZdwJEA3K0XhdlJ5_C2BpoI2xaqYx8bE9n3yQAT1dHcvYlwhkTE_AcByCe8n33OJiithgPUmtd4iM/pub?start=false&loop=false&delayms=3000) for this presentation.

**Comment by informaton** [comment]
### Webinar presentations
* NCI's nonwear algorithm in NHANES 2003-2004, Hyatt Moore ([.pdf](https://github.com/wadpac/oss-dev-webinar-series-pb-field/blob/master/slides/20200902_Moore_Corner%20cases%20in%20NCI's%20nonwear%20classification%20algorithm.pdf), [.gdoc](https://docs.google.com/presentation/d/e/2PACX-1vRUZdwJEA3K0XhdlJ5_C2BpoI2xaqYx8bE9n3yQAT1dHcvYlwhkTE_AcByCe8n33OJiithgPUmtd4iM/pub?start=false&loop=false&delayms=3000))
* Accelerometer Data from NHANES 2011-2014, Rick Troiano ([.pptx](https://github.com/wadpac/oss-dev-webinar-series-pb-field/blob/master/slides/20200902_Troiano%20-%20Github%20webinar.pptx))

### Manuscripts

* Troiano, Richard P., et al. "[Physical activity in the United States measured by accelerometer.](https://journals.lww.com/acsm-msse/Fulltext/2008/01000/Physical_Activity_in_the_United_States_Measured_by.25.aspx)" Medicine and science in sports and exercise 40.1 (2008): 181.
* Moore, Hyatt E., et al. "[Potential corner case cautions regarding publicly available implementations of the National Cancer Institute’s nonwear/wear classification algorithm for accelerometer data.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6312247/)" PLOS ONE 13.12 (2018): 1-11.

### NHANES Datasets
* NHANES Questionnaires, Datasets, and Related Documentation ([CDC website](https://wwwn.cdc.gov/nchs/nhanes/Default.aspx))
* List serve to get data release updates: https://www.cdc.gov/nchs/nhanes/nhanes_listserv.htm
* NHANES 2003-2004 ([CDC link](https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?BeginYear=2003))
* NHANES 2003-2004 physical activity monitor data dictionary ([PAWRAW_C.htm](https://wwwn.cdc.gov/Nchs/Nhanes/2003-2004/PAXRAW_C.htm))
* NHANES 2011-2012 ([CDC link](https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/SLQ_G.htm#SLD010H))


### Implementations of NCI's nonwear algorithm

#### National Cancer Institute's SAS code
* Website: 	https://epi.grants.cancer.gov/nhanes_pam/create.html
* Macro (/day):	https://epi.grants.cancer.gov/nhanes_pam/create.pam_perday.sas 

#### R Accelerometry project 
* Website: 	https://cran.r-project.org/web/packages/accelerometry/index.html
* Doc (.pdf): 	https://cran.r-project.org/web/packages/accelerometry/accelerometry.pdf

#### ActiLife
* White paper:	[What is the difference between the wear time validation algorithms](https://actigraph.desk.com/customer/en/portal/articles/2515570-what-is-the-difference-between-the-wear-time-validation-algorithms- )

**Comment by dijunrui** [comment]
FYI, there's a processed data package for NHANES 0304/0506 PA data, developed by Andrew Leroux. 
https://oslerinhealth.org/package/rnhanesdata

**Comment by vincentvanhees** [comment]
Closing this issue now. It is cited in https://github.com/wadpac/oss-dev-webinar-series-pb-field, so people should be able to find this issue.
