### ISSUE TITLE
Walking and/or Step detection

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/oss-dev-webinar-series-pb-field#7]
At presentation of #4 yesterday it became clear that there is expertise/interest in the ground around walking/step detection from accelerometer data.

At a future webinar we may want to discuss what algorithm and software are out there for detecting walking and/or steps stratified by sensor attachment location, number and type of sensors.

**Comment by informaton** [comment]
Presentation scheduled for 11 March CET 2020 by Marta and Matt.

**Comment by martakarass** [comment]
Part 1/2 slides: [Precise walking strides segmentation from raw accelerometry data: ADEPT method](https://docs.google.com/presentation/d/1ThrdQnFIfRH72fkNdpaiBaxdRB2brWvRgE1cT5hlA3A/edit?usp=sharing)

**Comment by informaton** [comment]
Did part 2/2 slides ever get posted?  They were good too.

**Comment by vincentvanhees** [comment]
@m-patterson?

**Comment by m-patterson** [comment]
Part 2/2 slides are available here - https://github.com/wadpac/oss-dev-webinar-series-pb-field/blob/master/slides/Gait%20Presentation.pptx

**Comment by m-patterson** [comment]
Slide link here - https://drive.google.com/file/d/1asPFFvcTOHhTZDmeptpuc89m9futueI3/view?usp=sharing

**Comment by vincentvanhees** [comment]
Closing this issue now. It is cited in https://github.com/wadpac/oss-dev-webinar-series-pb-field, so people should be able to find this issue.
